name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v8
        with:
          name: coda-coda-deepsea-public

      - name: nix-build
        run: nix-build
      - name: FunctionalCorrectness-compile-test
        run: nix-shell --run "FunctionalCorrectness-compile-test"
      - name: FunctionalCorrectness-no-axioms-test
        run: nix-shell --run "FunctionalCorrectness-no-axioms-test"
