name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixpkgs-20.09-darwin
      - uses: cachix/cachix-action@v8
        with:
          name: coda-coda-deepsea-public

      - name: nix-build
        run: nix-build
      - name: run-single-test
        run: run-single-test